from hashlib import sha256

from codepit_optimizer.manifest import build_file_declarations, build_manifest


def test_build_manifest_matches_codepit_v2_contract():
    manifest = build_manifest(
        benchmark_target_version="0.1.0",
        source_model_identifier="hf://sentence-transformers/all-MiniLM-L6-v2",
        source_model_revision="main",
        files=[
            ("model.onnx", "primary_model", "application/onnx", 128, "a" * 64),
            ("config.json", "config", "application/json", 64, "b" * 64),
            ("tokenizer.json", "tokenizer", "application/json", 64, "c" * 64),
            ("tokenizer_config.json", "tokenizer", "application/json", 64, "d" * 64),
        ],
        optimization_methods=["graph-optimization"],
        optimization_notes="candidate generated by codepit-model-optimizer",
    )

    assert manifest["artifact_lane"] == "onnx-browser-webgpu"
    assert manifest["model_class"] == "encoder-text-small"
    assert manifest["runtime_target"]["environment_family"] == "browser-webgpu"
    assert manifest["entrypoint"]["primary_model_logical_name"] == "model.onnx"
    assert manifest["entrypoint"]["supporting_files"] == [
        "config.json",
        "tokenizer.json",
        "tokenizer_config.json",
    ]
    assert manifest["optimization"]["methods"] == ["graph-optimization"]
    assert manifest["files"][0]["role"] == "primary_model"


def test_build_manifest_can_emit_gitlawb_provenance():
    manifest = build_manifest(
        benchmark_target_version="0.1.0",
        source_model_identifier="hf://sentence-transformers/all-MiniLM-L6-v2",
        source_model_revision="main",
        files=[
            ("model.onnx", "primary_model", "application/onnx", 128, "a" * 64),
        ],
        optimization_methods=["graph-optimization"],
        optimization_notes="candidate generated by codepit-model-optimizer",
        gitlawb={
            "did": "did:key:z6Mkcodepitagentprovenance",
            "repo": "codepit-agent-recipe",
            "commit": "0123456789abcdef0123456789abcdef01234567",
            "profile_url": "https://gitlawb.com/codepit-agent-recipe",
        },
    )

    assert manifest["provenance"]["gitlawb"] == {
        "did": "did:key:z6Mkcodepitagentprovenance",
        "repo": "codepit-agent-recipe",
        "commit": "0123456789abcdef0123456789abcdef01234567",
        "profile_url": "https://gitlawb.com/codepit-agent-recipe",
    }


def test_build_file_declarations_hashes_supported_bundle_files(tmp_path):
    (tmp_path / "tokenizer.json").write_text("tokenizer")
    (tmp_path / "ignored.bin").write_bytes(b"ignored")
    (tmp_path / "model.onnx").write_bytes(b"onnx")

    files = build_file_declarations(tmp_path)

    assert files == [
        ("model.onnx", "primary_model", "application/onnx", 4, sha256(b"onnx").hexdigest()),
        (
            "tokenizer.json",
            "tokenizer",
            "application/json",
            9,
            sha256(b"tokenizer").hexdigest(),
        ),
    ]
